# Generated by Django 4.1 on 2022-09-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description_group', models.CharField(max_length=640)),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('whatsapp_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('midle_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('is_godparents', models.BooleanField(choices=[(True, 'S'), (False, 'N')], default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('group_belongs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weddApp.groups')),
            ],
        ),
    ]
