# Generated by Django 4.1 on 2022-09-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='whatsapp_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

    ]
