# Generated by Django 4.1 on 2022-09-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddApp', '0002_guests_remove_webpage_topic_delete_accessrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='is_godparents',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')]),
        ),
        migrations.AlterField(
            model_name='guests',
            name='whatsapp_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
