# Generated by Django 4.1 on 2022-09-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddApp', '0004_alter_guests_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='is_confirmed',
            field=models.CharField(choices=[('Y', 'SIM'), ('N', 'NÃO'), ('O', 'N/I')], default='O', max_length=1),
        ),
    ]
