# Generated by Django 4.1 on 2022-09-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddApp', '0008_present_groups_id_alter_groups_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='group_belongs',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
