# Generated by Django 4.1 on 2022-09-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddApp', '0009_remove_guests_group_belongs_delete_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=40, unique=True)),
                ('description_group', models.CharField(max_length=640)),
            ],
        ),
        migrations.AddField(
            model_name='guests',
            name='group_belongs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weddApp.groups'),
        ),
    ]
