# Generated by Django 4.1 on 2022-09-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddApp', '0011_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='GroupMsg',
        ),
    ]
