# Generated by Django 4.1 on 2022-09-26 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddApp', '0012_rename_messages_groupmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndivdualMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_subject', models.CharField(max_length=120)),
                ('msg_type', models.CharField(choices=[('O', 'Comum'), ('I', 'Informações'), ('N', 'Novidades'), ('A', 'Alertas')], default='O', max_length=1)),
                ('msg_body', models.CharField(max_length=5000)),
                ('msg_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='weddApp.guests')),
                ('msg_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='weddApp.guests')),
            ],
        ),
    ]
