# Generated by Django 4.1 on 2022-09-27 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weddApp', '0013_indivdualmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmsg',
            name='msg_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indivdualmsg',
            name='msg_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
