# Generated by Django 4.1 on 2022-10-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddApp', '0014_groupmsg_msg_date_indivdualmsg_msg_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('relationship', models.CharField(choices=[('PARENTS', 'Pais'), ('RELATIVES', 'Familiares'), ('CHILDRENS', 'Filho(a)'), ('FRIENDS', 'Amigo(a)'), ('PARTNER', 'Parceiro(a)/Companheiro(a)')], max_length=10)),
                ('group_belongs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weddApp.groups')),
                ('who_confirmed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddApp.guests')),
            ],
        ),
        migrations.RenameModel(
            old_name='IndivdualMsg',
            new_name='IndividualMsg',
        ),
        migrations.DeleteModel(
            name='Present',
        ),
    ]
